# Tested using AWS CodeBuild
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # - cd awscdk/cluster && docker build -t $CLUSTER_IMAGE_REPO_NAME .
      # - docker tag $CLUSTER_IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CLUSTER_IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      -#  docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CLUSTER_IMAGE_REPO_NAME:$IMAGE_TAG
      # - cd ../..
      - aws ecr set-repository-policy --region $AWS_DEFAULT_REGION --repository-name $IMAGE_REPO_NAME --policy-text file://ecrpolicy.json
      # - aws ecr set-repository-policy --region $AWS_DEFAULT_REGION --repository-name $CLUSTER_IMAGE_REPO_NAME --policy-text file://ecrpolicy.json
