[codepipeline]
region = 'ap-southeast-2'
accountname = 'centauridau-mike'
account = '102460195799'
githubtokenname = 'GithubToken-5jhXVl'
githubtokenkey = 'github-oauth-token'
repoowner = 'Marakai'
reponame = 'TechTestApp'
