[codepipeline]
region = 'ap-southeast-2'
accountid = '102460195799'
githubtokenname = 'GithubToken-5jhXVl'
githubtokenkey = 'github-oauth-token'
githubrepoowner = 'Marakai'
githubreponame = 'TechTestApp'
buildbranch = 'feature/dbpasswordandinit'
