[cluster]
region = 'ap-southeast-2'
accountid = '102460195799'
dbuser= 'postgres'
dbname = 'app'
listenhost = '0.0.0.0'
listenport = 3000
dbhost = 'localhost'
ecrreponame = 'techtestapp_ecr'
containercpu = 512
containermem = 2048
containercount = 2
